# Generated by Django 3.1.7 on 2021-03-06 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20210305_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='pizza.user'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_pizzas', to='pizza.size'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(related_name='toppings', to='pizza.Topping'),
        ),
    ]
