# Generated by Django 3.1.7 on 2021-03-06 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_auto_20210305_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_timestamp', models.DateTimeField(auto_now_add=True)),
                ('order_price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('order_item', models.ManyToManyField(related_name='ordered', to='pizza.Pizza')),
                ('order_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pizza.user')),
            ],
        ),
    ]
